{"Volume": 9, "Published_Year": 2019, "Issue": "6", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 9, "Published_Year": 2019, "Issue": "5", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 9, "Published_Year": 2019, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 9, "Published_Year": 2019, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 9, "Published_Year": 2019, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 9, "Published_Year": 2019, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "12", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "11", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "10", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "9", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "8", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "7", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "6", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "5", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 8, "Published_Year": 2018, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "12", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "11", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "10", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "9", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "8", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "7", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "6", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "5", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 7, "Published_Year": 2017, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "12", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "11", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "10", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "9", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "8", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "7", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "6", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "5", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 6, "Published_Year": 2016, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "12", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "11", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "10", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "9", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "8", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "7", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "6", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "5", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 5, "Published_Year": 2015, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "12", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "11", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "10", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "9", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "8", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "7", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "6", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "5", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 4, "Published_Year": 2014, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "12", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "11", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "10", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "9", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "8", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "7", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "6", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "5", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 3, "Published_Year": 2013, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 2, "Published_Year": 2012, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 2, "Published_Year": 2012, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 2, "Published_Year": 2012, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 2, "Published_Year": 2012, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 1, "Published_Year": 2011, "Issue": "4", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 1, "Published_Year": 2011, "Issue": "3", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 1, "Published_Year": 2011, "Issue": "2", "Journal": "AIP Advances", "Publisher": "AIP"}
{"Volume": 1, "Published_Year": 2011, "Issue": "1", "Journal": "AIP Advances", "Publisher": "AIP"}
