{"Volume": 9, "Published_Year": 2019, "Journal": "AIP Advances", "Issue": "6", "Link": "https://aip.scitation.org/toc/adv/9/6"}
{"Volume": 9, "Published_Year": 2019, "Journal": "AIP Advances", "Issue": "5", "Link": "https://aip.scitation.org/toc/adv/9/5"}
{"Volume": 9, "Published_Year": 2019, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/9/4"}
{"Volume": 9, "Published_Year": 2019, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/9/3"}
{"Volume": 9, "Published_Year": 2019, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/9/2"}
{"Volume": 9, "Published_Year": 2019, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/9/1"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "12", "Link": "https://aip.scitation.org/toc/adv/8/12"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "11", "Link": "https://aip.scitation.org/toc/adv/8/11"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "10", "Link": "https://aip.scitation.org/toc/adv/8/10"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "9", "Link": "https://aip.scitation.org/toc/adv/8/9"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "8", "Link": "https://aip.scitation.org/toc/adv/8/8"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "7", "Link": "https://aip.scitation.org/toc/adv/8/7"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "6", "Link": "https://aip.scitation.org/toc/adv/8/6"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "5", "Link": "https://aip.scitation.org/toc/adv/8/5"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/8/4"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/8/3"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/8/2"}
{"Volume": 8, "Published_Year": 2018, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/8/1"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "12", "Link": "https://aip.scitation.org/toc/adv/7/12"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "11", "Link": "https://aip.scitation.org/toc/adv/7/11"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "10", "Link": "https://aip.scitation.org/toc/adv/7/10"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "9", "Link": "https://aip.scitation.org/toc/adv/7/9"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "8", "Link": "https://aip.scitation.org/toc/adv/7/8"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "7", "Link": "https://aip.scitation.org/toc/adv/7/7"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "6", "Link": "https://aip.scitation.org/toc/adv/7/6"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "5", "Link": "https://aip.scitation.org/toc/adv/7/5"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/7/4"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/7/3"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/7/2"}
{"Volume": 7, "Published_Year": 2017, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/7/1"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "12", "Link": "https://aip.scitation.org/toc/adv/6/12"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "11", "Link": "https://aip.scitation.org/toc/adv/6/11"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "10", "Link": "https://aip.scitation.org/toc/adv/6/10"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "9", "Link": "https://aip.scitation.org/toc/adv/6/9"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "8", "Link": "https://aip.scitation.org/toc/adv/6/8"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "7", "Link": "https://aip.scitation.org/toc/adv/6/7"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "6", "Link": "https://aip.scitation.org/toc/adv/6/6"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "5", "Link": "https://aip.scitation.org/toc/adv/6/5"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/6/4"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/6/3"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/6/2"}
{"Volume": 6, "Published_Year": 2016, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/6/1"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "12", "Link": "https://aip.scitation.org/toc/adv/5/12"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "11", "Link": "https://aip.scitation.org/toc/adv/5/11"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "10", "Link": "https://aip.scitation.org/toc/adv/5/10"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "9", "Link": "https://aip.scitation.org/toc/adv/5/9"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "8", "Link": "https://aip.scitation.org/toc/adv/5/8"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "7", "Link": "https://aip.scitation.org/toc/adv/5/7"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "6", "Link": "https://aip.scitation.org/toc/adv/5/6"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "5", "Link": "https://aip.scitation.org/toc/adv/5/5"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/5/4"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/5/3"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/5/2"}
{"Volume": 5, "Published_Year": 2015, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/5/1"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "12", "Link": "https://aip.scitation.org/toc/adv/4/12"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "11", "Link": "https://aip.scitation.org/toc/adv/4/11"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "10", "Link": "https://aip.scitation.org/toc/adv/4/10"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "9", "Link": "https://aip.scitation.org/toc/adv/4/9"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "8", "Link": "https://aip.scitation.org/toc/adv/4/8"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "7", "Link": "https://aip.scitation.org/toc/adv/4/7"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "6", "Link": "https://aip.scitation.org/toc/adv/4/6"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "5", "Link": "https://aip.scitation.org/toc/adv/4/5"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/4/4"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/4/3"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/4/2"}
{"Volume": 4, "Published_Year": 2014, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/4/1"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "12", "Link": "https://aip.scitation.org/toc/adv/3/12"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "11", "Link": "https://aip.scitation.org/toc/adv/3/11"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "10", "Link": "https://aip.scitation.org/toc/adv/3/10"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "9", "Link": "https://aip.scitation.org/toc/adv/3/9"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "8", "Link": "https://aip.scitation.org/toc/adv/3/8"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "7", "Link": "https://aip.scitation.org/toc/adv/3/7"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "6", "Link": "https://aip.scitation.org/toc/adv/3/6"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "5", "Link": "https://aip.scitation.org/toc/adv/3/5"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/3/4"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/3/3"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/3/2"}
{"Volume": 3, "Published_Year": 2013, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/3/1"}
{"Volume": 2, "Published_Year": 2012, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/2/4"}
{"Volume": 2, "Published_Year": 2012, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/2/3"}
{"Volume": 2, "Published_Year": 2012, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/2/2"}
{"Volume": 2, "Published_Year": 2012, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/2/1"}
{"Volume": 1, "Published_Year": 2011, "Journal": "AIP Advances", "Issue": "4", "Link": "https://aip.scitation.org/toc/adv/1/4"}
{"Volume": 1, "Published_Year": 2011, "Journal": "AIP Advances", "Issue": "3", "Link": "https://aip.scitation.org/toc/adv/1/3"}
{"Volume": 1, "Published_Year": 2011, "Journal": "AIP Advances", "Issue": "2", "Link": "https://aip.scitation.org/toc/adv/1/2"}
{"Volume": 1, "Published_Year": 2011, "Journal": "AIP Advances", "Issue": "1", "Link": "https://aip.scitation.org/toc/adv/1/1"}
